spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ${password}
  redis:
    database: 3
    host: localhost
    port: 6379
    password: null
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: mappers/ProductMapper.xml